### ISSUE TITLE
各后端文件夹内不存在requirements.txt

### ISSUE THREAD

**Issue by StevenArai** [TochusC/ai-assistant-teaching-website#5]
各后端文件夹内不存在requirements.txt, 导致我在尝试运行AvatarServer时出现错误：
![image](https://github.com/user-attachments/assets/8e8de3cd-c899-4729-aa63-ff73a1003d75)
该错误即使在安装sparkai后依然无法解决。希望尽快上传requirement.txt

**Comment by StevenArai** [comment]
我已在python3.9成功配置环境，准备尝试制作requirement.txt

**Comment by TochusC** [comment]
感谢制作requirement.txt，我目前对该项目的维护还不够完善，接下来准备改进一下。

**Comment by TochusC** [comment]
首先感谢您的关注😊😊，我现在已向AvatarServer及backend两个Django后端添加了相应的requirements.txt文件。
值得注意的是：本项目是为了参加比赛而诞生，因此加入了许多花哨冗余的功能，该项目唯一值得关注的可能就仅仅只是“智能助理”部分了。
智能助理的实现需要调用大量的外部服务API（大语言模型、语音转文本、文本转语音等），该部分API目前使用的仍然是我个人申请的API接口，可能会因为费用超限或超出有效期等原因而**不能正常工作**，请您可以将其中的代码作为参考，并换成适合自己环境的相应API，例如ChatGPT或是Microsoft提供的TTS服务等⚡。
祝好🌟
